### PR TITLE
Added ltscombine tool.

### PR DESCRIPTION
**Pull request by Willem49**
The ltscombine tool allows the user to combine a multitude of labelled transition systems (LTSs) into a new LTS. The tool also contains four options that simulate the comm, hide, allow and block operators of mCRL2. These can be supplied in a text file where the allow and block options are a list of multi-actions seperated by commas, for example a|b,c|d. The hide option is a list of singular actions seperated by commas, for example a,b,c. And lastly the communications operator, similar to the mCRL2 syntax, is a list of synchronisations seperated by commas, where a synchronisation is represented as multi-action -> result action, for example a|b -> c. These operations are applied in the order of, communications, blocking, allowing and lastly hiding. 

An example command of the tool could look as follows:
ltscombine lts-1.lts lts-2.lts lts-3.lts result.lts --comm=comms.txt --allow=allow.txt --block=block.txt --hide=hide.txt

Here the LTSs in lts-1.lts, lts-2.lts and lts-3.lts are combined into a new LTS, on which the communications of comms.txt are applied, only the multi-actions of allow.txt are used, the multi-actions of block.txt are blocked and the actions of hide.txt are hiden. This resulting LTS is then saved to result.lts. If the allow file is empty, the tool will allow any action to be used in the resulting LTS.

### CODE REVIEW

**Comment by jkeiren** [comment]
First questions based on the description in the PR: 

* Suppose we want to combine LTSes lts-1 and lts-2, what exactly is the order that is applied. Based on the typical use pattern of mCRL2, and the description given above, I expect it is:
hide(hide.txt, block(block.txt, allow(allow.txt, comm(comm.txt, lts-1 || lts-2)))).
* You write that block.txt contains multi-actions. The semantics of the block-operator on processes uses a set B containing action names that are not allowed (so names of actions, not multi-actions). The allow operator works on a set V of multi-actions. The sets provided for ltscombine should at least be consistent with the ones used in mCRL2 processes.

**Comment by Willem49** [comment]
* The order of combining two LTSes lts-1 and lts-2, is indeed hide(hide.txt, block(block.txt, allow(allow.txt, comm(comm.txt, lts-1 || lts-2)))).
* The block operator now indeed works on a set of action names, and the allow operator works on a set of multi-actions.

**Comment by mlaveaux** [comment]
Overall I think it looks good. Perhaps some string comparisons could be replaced by action_label (pointer) comparisons and I will have to think about adding random tests.

**Review by mlaveaux — APPROVED** [review]
I can imagine that the command line argument parsing could be made more robust before actually releasing the tool, but for an experimental tool it seems fine by me. For example passing --allow="a b" will simply allow a non-existing action "a b".

**Pull request merged**
