### PR TITLE
Fix hidpi linux

### LINKED ISSUE #1559: LTSView: problem with selecting objects on linux
Clicking on a cluster or node does not select the object on Linux (in LTSView), but clicking near the right bottom selects an object in the center. This might have something to do with my HiDPI display.

### PR DESCRIPTION
**Pull request by wsinnema**
This should fix #1559 and #1560. Not tested under Windows or MacOS.

### CODE REVIEW

**Comment by tneele** [comment]
We have not been able to reproduce the issue with selecting objects on a scaled display so far. We tried this on Ubuntu and Fedora.

There are several issues when running ltsview with these changes on Wayland and on Windows:

- When clicking on any object, the whole windows becomes black, except for the window decorations.
- Under Wayland, all objects that are drawn with transparency reveal the content of other windows beneath ltsview. Example: when I run ltsview from a terminal, I can see part of the contents of the terminal through ltsgraph's objects.

Maybe you can elaborate a bit more on your setup and what you observe?

**Comment by wsinnema** [comment]
When I tested the current version on wayland, nothing was visible in the OpenGL view.

**Comment by wsinnema** [comment]
When I ran the current version (git master) under Wayland,  the OpenGL view is invisible. I also noticed the transparency, but didn't find an easy way to fix it.

In the current version, the location of the mouse is is not the same location where the event fires. When inspecting this, I discovered that the viewport dimensions are doubled when in the selectObject method. The added method call is supposed to fix it, but I'm not sure whether it is the right solution.

I've tested this on an Arch Linux system with QT 5.13, on both Xorg (tested using i3 and KDE plasma) and Wayland (tested on Gnome 3.34 and Kde Plasma 5.16). All of this both with the Open Source Intel and AMDGPU GPU drivers. For HiDPI under Xorg, the following environment variables are set:

QT_SCALE_FACTOR=2
QT_FONT_DPI=92
QT_FONT_DPI=92

Not that on Gnome-wayland, the Xorg version of LTSView is working perfectly.
LTSView-Wayland-Plasma
LTSView Gnome Wayland

**Comment by tneele** [comment]
Thanks for the info. I had observed the same issues (invisible QGLView) with the current version under Wayland.

I can now reproduce the issue with selecting objects when setting QT_SCALE_FACTOR to 2. The regression on Windows (and for me also on Wayland) that the whole window becomes black when clicking something needs to be resolved though before we can merge these changes. I don't have time in the coming weeks to investigate this myself. Perhaps one of the other maintainers can have a look.

**Comment by mlaveaux** [comment]
I have managed to solve the black screen issue under Wayland; see the following [patch.txt](https://github.com/mCRL2org/mCRL2/files/4292222/blackscreen.txt). The export bitmap functionality is currently broken, but I am also not sure whether this has worked (for me) before. Some testing under X11, MacOS and Windows is probably necessary before we can integrate these changes.

**Pull request merged**
